shallow_clone: true

version: '{build}'

os:
  - Visual Studio 2019
  - Visual Studio 2015
  - Visual Studio 2013

platform:
  - x64
  - x86

configuration:
  - Release

matrix:
  exclude:
    - os: Visual Studio 2015
      #platform: x86
    - os: Visual Studio 2013
      #platform: x86

build:
  verbosity: detailed

environment:
  CMAKE_INSTALL_PREFIX: C:\projects\stir\install\
  matrix:
    - os: Visual Studio 2019
      BOOST_ROOT: C:\Libraries\boost_1_73_0
    - os: Visual Studio 2015
      BOOST_ROOT: C:\Libraries\boost_1_63_0
    - os: Visual Studio 2013
      BOOST_ROOT: C:\Libraries\boost_1_63_0

build_script:
  - mkdir build
  - mkdir install
  - cd build
  - cmake.exe .. -DCMAKE_INSTALL_PREFIX="C:\projects\stir\install" -DCMAKE_BUILD_TYPE=%CONFIGURATION%  -DCMAKE_CONFIGURATION_TYPES=%CONFIGURATION% -DSTIR_OPENMP=ON
  - cmake.exe --build . --config %CONFIGURATION%
  - cmake.exe --build . --target install --config %CONFIGURATION%

test_script:
  - cd C:\projects\stir\build
  - ctest -VV -C %CONFIGURATION%
  - cd ..\recon_test_pack
  - run_tests --nointbp "C:\projects\stir\install\bin\"
